Repository boostcampwm-2021/android06-GagyeBoost, pull requests merged in 2021-11, with the labels that each got.

#54 [리팩토링] 카테고리 타입 상수화, 달력 뷰 수정
  app/src/main/java/com/example/gagyeboost/di/AppModules.kt
  app/src/main/java/com/example/gagyeboost/model/data/AccountBook.kt
  app/src/main/java/com/example/gagyeboost/model/data/Category.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendar.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendarAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/AddCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/res/layout/item_rv_detail.xml
Labels: refactoring

#57 HomeViewModel 리팩토링, 버그 수정
  app/build.gradle
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendar.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendarAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/DateDetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/NumberPickerDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/home/add/AddFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/CategoryIconAdapter.kt
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/values/strings.xml
Labels: bug, refactoring

#60 [통계] 통계탭 기본 레이아웃 및 Fragment 구현
  app/src/main/java/com/example/gagyeboost/di/AppModules.kt
  app/src/main/java/com/example/gagyeboost/model/data/StatRecordItem.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatResultAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsViewModel.kt
  app/src/main/res/layout/fragment_statistics.xml
  app/src/main/res/layout/item_stat_record.xml
  app/src/main/res/values/strings.xml
Labels: feature, UI

#62 [지도] 지도 초기 설정 및 마커 찍기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/res/drawable-v24/background_gradation_circle.xml
  app/src/main/res/drawable/background_white_radius_5dp.xml
  app/src/main/res/drawable/ic_gps.xml
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/fragment_select_position.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: feature

#73 [상세페이지] 레이아웃, ViewModel 및 Activity 구성
  .github/workflows/android.yml
  .gitignore
  app/build.gradle
  app/src/androidTest/java/com/example/gagyeboost/DatabaseTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/di/AppModules.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/AccountBook.kt
  app/src/main/java/com/example/gagyeboost/model/data/Category.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateDetailItem.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendar.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendarAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/DateDetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/NumberPickerDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/home/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/RecordDetailViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/add/AddFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/AddCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/CategoryIconAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/res/layout/activity_record_detail.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_update_category.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/menu/update_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  keystore/android06
Labels: feature, UI

#75 [수입/지출 추가] 위치 사용 권한 요청 및 지도 설정
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gagyeboost/common/GPSUtils.kt
  app/src/main/java/com/example/gagyeboost/di/AppModules.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/PlaceDetailResponse.kt
  app/src/main/java/com/example/gagyeboost/model/remote/GooglePlaceClient.kt
  app/src/main/java/com/example/gagyeboost/model/remote/GooglePlaceService.kt
  app/src/main/java/com/example/gagyeboost/model/remote/HeaderInterceptor.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressResultFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/res/drawable/background_bottom_sheet.xml
  app/src/main/res/layout/dialog_bottom_address_result.xml
  app/src/main/res/layout/fragment_select_position.xml
  app/src/main/res/layout/item_address.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: feature

#81 [지도] 필터링 구현
  .gitignore
  app/build.gradle
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/di/AppModules.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateItem.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterMoneyDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterMoneyTypeDialog.kt
  app/src/main/res/drawable/background_expense_btn.xml
  app/src/main/res/drawable/background_white_radius_20dp.xml
  app/src/main/res/drawable/bottom_sheet_background.xml
  app/src/main/res/drawable/btn_selected_false.xml
  app/src/main/res/layout/dialog_filter.xml
  app/src/main/res/layout/dialog_filter_money.xml
  app/src/main/res/layout/dialog_filter_money_type.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_select_position.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, review

#80 [지도] 상세목록 표시
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/ui/map/DetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapDetailFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/res/layout/dialog_filter.xml
  app/src/main/res/layout/dialog_map_bottom_detail.xml
  app/src/main/res/layout/item_rv_detail.xml
Labels: review

#79 [수입/지출 상세화면] 내역 수정, 삭제
  .github/workflows/android.yml
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/common/GPSUtils.kt
  app/src/main/java/com/example/gagyeboost/di/AppModules.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateDetailItem.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateItem.kt
  app/src/main/java/com/example/gagyeboost/model/data/PlaceDetailResponse.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/model/remote/GooglePlaceClient.kt
  app/src/main/java/com/example/gagyeboost/model/remote/GooglePlaceService.kt
  app/src/main/java/com/example/gagyeboost/model/remote/HeaderInterceptor.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendarAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/RecordDetailViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/DateDetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressResultFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/DetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapDetailFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterMoneyDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterMoneyTypeDialog.kt
  app/src/main/res/drawable-v24/background_gradation_circle.xml
  app/src/main/res/drawable/background_bottom_sheet.xml
  app/src/main/res/drawable/background_expense_btn.xml
  app/src/main/res/drawable/background_white_radius_20dp.xml
  app/src/main/res/drawable/background_white_radius_5dp.xml
  app/src/main/res/drawable/bottom_sheet_background.xml
  app/src/main/res/drawable/btn_selected_false.xml
  app/src/main/res/drawable/ic_gps.xml
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/layout/activity_record_detail.xml
  app/src/main/res/layout/bottom_sheet_category.xml
  app/src/main/res/layout/dialog_bottom_address_result.xml
  app/src/main/res/layout/dialog_filter_money.xml
  app/src/main/res/layout/dialog_filter_money_type.xml
  app/src/main/res/layout/dialog_map_bottom_detail.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_select_position.xml
  app/src/main/res/layout/item_address.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: feature, review

#112 [지도] 클러스터링 구현, category 필터 클릭 시 화면 구현
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/common/GPSUtils.kt
  app/src/main/java/com/example/gagyeboost/di/AppModules.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/ClusterItems.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateDetailItem.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendarAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/add/AddFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/DateDetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/ClusterRender.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapDetailFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/CategoryFilterAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterMoneyDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterMoneyTypeDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchFragment.kt
  app/src/main/res/drawable/bottom_sheet_background.xml
  app/src/main/res/drawable/expense_enabled_btn_selector.xml
  app/src/main/res/drawable/income_enabled_btn_selector.xml
  app/src/main/res/layout/activity_record_detail.xml
  app/src/main/res/layout/bottom_sheet_category.xml
  app/src/main/res/layout/dialog_filter_category.xml
  app/src/main/res/layout/dialog_filter_money.xml
  app/src/main/res/layout/dialog_filter_money_type.xml
  app/src/main/res/layout/fragment_add.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_update_category.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/layout/item_rv_filter_category.xml
  app/src/main/res/menu/update_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  keystore/android06
Labels: feature

#124 [지도] 카테고리 필터 구현
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryDialog.kt
  app/src/main/res/drawable/background_white_radius_20dp_stroke_green.xml
  app/src/main/res/layout/activity_address_result.xml
  app/src/main/res/layout/dialog_filter_category.xml
  app/src/main/res/layout/dialog_filter_money.xml
  app/src/main/res/layout/item_address.xml
  app/src/main/res/layout/item_rv_filter_category.xml
  app/src/main/res/values/strings.xml
Labels: feature

#132 [통계] 원형그래프 및 막대 그래프 수정
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/model/data/StatRecordItem.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/CustomPieNumberFormatter.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatResultAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsViewModel.kt
  app/src/main/res/layout/fragment_statistics.xml
  app/src/main/res/layout/item_stat_record.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: feature

#143 [검색] 쿼리, 레이아웃
  .github/workflows/android.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/common/GPSUtils.kt
  app/src/main/java/com/example/gagyeboost/di/AppModules.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/ClusterItems.kt
  app/src/main/java/com/example/gagyeboost/model/data/PlaceDetailResponse.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/model/remote/HeaderInterceptor.kt
  app/src/main/java/com/example/gagyeboost/model/remote/KakaoAPIClient.kt
  app/src/main/java/com/example/gagyeboost/model/remote/KakaoAPIService.kt
  app/src/main/java/com/example/gagyeboost/ui/address/AddressResultActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/address/AddressResultViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressPagingSource.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressResultFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/ClusterRender.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapDetailFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchResultFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/background_outline_radius_20dp.xml
  app/src/main/res/drawable/background_white_radius_20dp_stroke_green.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/layout/activity_address_result.xml
  app/src/main/res/layout/dialog_bottom_address_result.xml
  app/src/main/res/layout/dialog_filter_category.xml
  app/src/main/res/layout/dialog_filter_money.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/layout/fragment_select_position.xml
  app/src/main/res/layout/item_address.xml
  app/src/main/res/layout/item_rv_filter_category.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: feature, UI, review

#176 버그 fix, 검색 결과 없을 시 피드백 주기
  app/src/main/java/com/example/gagyeboost/common/GPSUtils.kt
  app/src/main/java/com/example/gagyeboost/model/remote/KakaoAPIService.kt
  app/src/main/java/com/example/gagyeboost/ui/address/AddressResultActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/add/AddFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/AddCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressPagingSource.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/LoadStateAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchFragment.kt
  app/src/main/res/layout/activity_address_result.xml
  app/src/main/res/layout/activity_record_detail.xml
  app/src/main/res/layout/fragment_add.xml
  app/src/main/res/layout/item_address_footer.xml
  app/src/main/res/values/strings.xml
Labels: bug, feature, Crash

#178 [Detail] 마커 커스텀, 카테고리 삭제 기능 추가
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/ClusterRender.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/res/drawable/ic_expense_marker.xml
  app/src/main/res/drawable/ic_income_marker.xml
  app/src/main/res/values/strings.xml
Labels: feature

#187 버그 fix
  app/src/main/java/com/example/gagyeboost/common/Utils.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendarAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterMoneyDialog.kt
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/values/themes.xml
Labels: bug, fixed

#193 [Fix] 네비게이션 바 연타시 크래시 되는 현상 수정
  app/build.gradle
  app/src/main/java/com/example/gagyeboost/ui/MainActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
Labels: bug, Crash

#214 [통계, 검색] 버그 해결 및 UX 개선
  README.md
  app/build.gradle
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/common/GPSUtils.kt
  app/src/main/java/com/example/gagyeboost/common/Utils.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/AccountBook.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/model/remote/KakaoAPIService.kt
  app/src/main/java/com/example/gagyeboost/ui/MainActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/address/AddressResultActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/address/AddressResultViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/CustomCalendarAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/add/AddFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/AddCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressPagingSource.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/LoadStateAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/ClusterRender.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterMoneyDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchCategoryDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsViewModel.kt
  app/src/main/res/drawable/ic_default_marker.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_expense_marker.xml
  app/src/main/res/drawable/ic_income_marker.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/activity_address_result.xml
  app/src/main/res/layout/activity_record_detail.xml
  app/src/main/res/layout/fragment_add.xml
  app/src/main/res/layout/fragment_add_category.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_update_category.xml
  app/src/main/res/layout/item_address_footer.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: bug, feature, fixed

#216 [상세화면] 상세화면 관련 UX 수정
  README.md
  app/build.gradle
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDatabase.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/DateDetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/map/DetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapDetailFragment.kt
  app/src/main/res/layout/activity_record_detail.xml
  app/src/main/res/layout/fragment_add.xml
  app/src/main/res/values/strings.xml
Labels: feature

#218 [지도] 클러스터링 최적화
  README.md
  app/build.gradle
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/model/data/CameraBounds.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/map/ClusterRender.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/values/strings.xml
Labels: refactoring

#224 데이터 남아있는 버그, 코드 리팩토링
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateDetailItem.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateItem.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/ui/MainActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/NumberPickerDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/home/add/AddFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/AddCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/CategoryIconListFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/DateDetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapDetailFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsFragment.kt
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: bug, refactoring

#231 [지도] 버그 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/common/Utils.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateDetailItem.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateItem.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDatabase.kt
  app/src/main/java/com/example/gagyeboost/ui/MainActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/NumberPickerDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/home/add/AddFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/AddCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/CategoryIconListFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/DateDetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressPagingSource.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/DetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapDetailFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchCategoryDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsViewModel.kt
  app/src/main/res/layout/activity_record_detail.xml
  app/src/main/res/layout/fragment_add.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: bug, fixed

#233 코드 리팩토링, 카테고리 수정 상태 유지 버그 수정
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/CameraBounds.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateItem.kt
  app/src/main/java/com/example/gagyeboost/model/data/PlaceDetailResponse.kt
  app/src/main/java/com/example/gagyeboost/model/data/RecordDetailData.kt
  app/src/main/java/com/example/gagyeboost/model/data/enumClass.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/add/AddFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/ClusterRender.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchCategoryDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsViewModel.kt
  app/src/main/res/drawable/background_white_radius_20dp_stroke_expense.xml
  app/src/main/res/layout/activity_record_detail.xml
  app/src/main/res/layout/fragment_add.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: bug, refactoring, UI

#235 버그 수정
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/gagyeboost/common/Const.kt
  app/src/main/java/com/example/gagyeboost/model/Repository.kt
  app/src/main/java/com/example/gagyeboost/model/data/CameraBounds.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateDetailItem.kt
  app/src/main/java/com/example/gagyeboost/model/data/DateItem.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDAO.kt
  app/src/main/java/com/example/gagyeboost/model/local/AccountBookDatabase.kt
  app/src/main/java/com/example/gagyeboost/ui/MainActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/AddViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/HomeViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/home/NumberPickerDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/home/add/AddFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/category/CategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/AddCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/CategoryIconListFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/categoryControl/UpdateCategoryFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/DateDetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/home/detail/RecordDetailActivity.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/AddressPagingSource.kt
  app/src/main/java/com/example/gagyeboost/ui/home/selectPosition/SelectPositionFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/ClusterRender.kt
  app/src/main/java/com/example/gagyeboost/ui/map/DetailAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapDetailFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/map/MapViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/map/filter/FilterCategoryDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchCategoryAdapter.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchCategoryDialog.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/search/SearchViewModel.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsFragment.kt
  app/src/main/java/com/example/gagyeboost/ui/statstics/StatisticsViewModel.kt
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/layout/activity_record_detail.xml
  app/src/main/res/layout/fragment_add.xml
  app/src/main/res/layout/fragment_add_category.xml
  app/src/main/res/layout/fragment_category.xml
  app/src/main/res/layout/fragment_map.xml
  app/src/main/res/layout/fragment_update_category.xml
  app/src/main/res/layout/item_category.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/layout/item_rv_detail.xml
  app/src/main/res/navigation/navigation_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: bug, feature
